name: Deploy Backend

on:
  push:
    branches:
      - main  # or your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.216.74.132 "
            cd /home/ec2-user/SavorAI/backend &&
            git pull &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            deactivate &&
            sudo systemctl restart recipe-backend
          "
